import type { StoredLead } from "@/lib/store/import-history";

/** Seed leads so Manage / Dashboard look enterprise-ready before first import. */
export const DEMO_LEADS: StoredLead[] = [
  {
    id: "demo-1",
    created_at: "2026-07-08T10:12:00Z",
    name: "Ananya Rao",
    email: "ananya.rao@example.com",
    country_code: "+91",
    mobile_without_country_code: "9876543210",
    company: "Rao Estates",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    lead_owner: "ravi@groweasy.ai",
    crm_status: "GOOD_LEAD_FOLLOW_UP",
    crm_note: "Site visit Saturday",
    data_source: "meridian_tower",
    possession_time: "Ready to move",
    description: "3BHK east facing",
    importedAt: "2026-07-08T10:15:00Z",
    sourceFile: "sample_leads_test.csv",
    qualityState: "clean",
    confidence: 96,
  },
  {
    id: "demo-2",
    created_at: "2026-07-08T11:02:00Z",
    name: "Kiran Teja",
    email: "kiran.teja@work.in",
    country_code: "+91",
    mobile_without_country_code: "9000011122",
    company: "",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    lead_owner: "priya@groweasy.ai",
    crm_status: "DID_NOT_CONNECT",
    crm_note: "Call after 7pm",
    data_source: "sarjapur_plots",
    possession_time: "Q4 2026",
    description: "",
    importedAt: "2026-07-08T11:05:00Z",
    sourceFile: "whatsapp-agent-sheet.csv",
    qualityState: "needs_review",
    confidence: 72,
  },
  {
    id: "demo-3",
    created_at: "2026-07-09T09:40:00Z",
    name: "Meera Iyer",
    email: "meera@iyer.co",
    country_code: "+91",
    mobile_without_country_code: "9001122334",
    company: "Iyer & Co",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    lead_owner: "priya@groweasy.ai",
    crm_status: "SALE_DONE",
    crm_note: "Token paid",
    data_source: "sarjapur_plots",
    possession_time: "Immediate",
    description: "Closed via LOD campaign",
    importedAt: "2026-07-09T09:44:00Z",
    sourceFile: "zoho-crm-export.csv",
    qualityState: "clean",
    confidence: 94,
  },
  {
    id: "demo-4",
    created_at: "2026-07-09T14:20:00Z",
    name: "Vikram Nair",
    email: "vikram.nair@outlook.com",
    country_code: "+91",
    mobile_without_country_code: "9988776655",
    company: "",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    lead_owner: "ravi@groweasy.ai",
    crm_status: "BAD_LEAD",
    crm_note: "Not interested",
    data_source: "eden_park",
    possession_time: "",
    description: "",
    importedAt: "2026-07-09T14:22:00Z",
    sourceFile: "facebook-leads.csv",
    qualityState: "needs_review",
    confidence: 68,
  },
  {
    id: "demo-5",
    created_at: "2026-07-10T08:05:00Z",
    name: "Fatima Shaik",
    email: "fatima.s@mail.com",
    country_code: "+91",
    mobile_without_country_code: "9123456780",
    company: "",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    lead_owner: "ravi@groweasy.ai",
    crm_status: "GOOD_LEAD_FOLLOW_UP",
    crm_note: "Prefers Telugu callback",
    data_source: "leads_on_demand",
    possession_time: "Immediate",
    description: "WhatsApp fwd",
    importedAt: "2026-07-10T08:08:00Z",
    sourceFile: "whatsapp-agent-sheet.csv",
    qualityState: "clean",
    confidence: 91,
  },
];

export const DEMO_TEAM = [
  { name: "Varun Kumar", email: "varun@groweasy.ai", role: "Owner", status: "Active" },
  { name: "Ravi Sharma", email: "ravi@groweasy.ai", role: "Sales lead", status: "Active" },
  { name: "Priya Nair", email: "priya@groweasy.ai", role: "Agent", status: "Active" },
  { name: "Sneha Reddy", email: "sneha@groweasy.ai", role: "Agent", status: "Invited" },
];

export const DEMO_CAMPAIGNS = [
  {
    name: "Meridian Tower — FB Lead Ads",
    channel: "Facebook",
    status: "Live",
    leads: 128,
    cpl: "₹42",
  },
  {
    name: "Sarjapur Plots — Google",
    channel: "Google Ads",
    status: "Live",
    leads: 86,
    cpl: "₹55",
  },
  {
    name: "LOD WhatsApp blast",
    channel: "WhatsApp",
    status: "Paused",
    leads: 41,
    cpl: "₹18",
  },
];

export const DEMO_ENGAGE_QUEUE = [
  {
    name: "Ananya Rao",
    channel: "WhatsApp",
    nextAction: "Send brochure",
    due: "Today 4:00 PM",
    owner: "Ravi",
  },
  {
    name: "Kiran Teja",
    channel: "Call",
    nextAction: "Callback — evening",
    due: "Today 7:30 PM",
    owner: "Priya",
  },
  {
    name: "Fatima Shaik",
    channel: "WhatsApp",
    nextAction: "Confirm site visit",
    due: "Tomorrow 11:00 AM",
    owner: "Ravi",
  },
];
